kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  {{ .Values.storageClassName }}
  namespace: {{ .Values.namespace }}
provisioner: {{ .Values.provisioner }}
allowVolumeExpansion: {{ .Values.allowVolumeExpansion }}
parameters:
  skuName: {{ .Values.parameters.skuName }}

