# Default values for azure-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: regscale

deployment:
  name: regscale-deploy
replicaCount: 1

image:
  repository: c2labs/atlasity:latest
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  name: regscale-svc
  type: ClusterIP
  port: 80
  targetPort: 80

volumeMounts:
  mountPath: "/regscale/files"
  name: regscale-files 
  
configMapRef:
  name: regscale-config
StoredFilesPath: "/regscale/files"
FileSizeLimit: "104857600"

secretRef:
  name: regscale-secrets
WTSecretKey: "JWTSecretKeyFromSomeWhere6789012"
SQLConn: "Server=tcp:yourdatabase.database.windows.net,1433;Initial Catalog=ATLAS;Persist Security Info=False;User ID=youruserID;Password=yourPassword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
EncryptionKey: "YourEncryptionKeyFromSomeWhere12"

pvc:
  name: regscale-pvc

storageClassName: azurefile
capacity:
  storage: 1Gi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}



