name: Helm Publish

on:
  push:
    branches: [ echehelm ] 

    # paths-ignore:
    #   - README.md
jobs:
  publish-helmchart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Create index file
    #   run: helm repo index $GITHUB_WORKSPACE/charts  

    - name: Create empty gh-pages branches
      run: |
        git checkout --orphan gh-pages
        

