name: Helm Publish

on:
  push:
    branches: [ echehelm ] 

    # paths-ignore:
    #   - README.md
jobs:
  publish-helmchart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create gh-page branch
      run: | 
           git switch --orphan gh-pages1
           git commit --allow-empty -m "Initial commit"
           git push -u origin gh-pages1
