name: Publish Azure Helm Chart To ACR

on:
  push:
    branches: [ none ] 

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: latest
  ACR_NAME: regscalecontainerregistry
  ACR_REPO_NAME: helmdemo/vote-app
  ACR_REGISTRY: regscalecontainerregistry
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
  ACR_SERVER: regscalecontainerregistry.azurecr.io
jobs:
  push_helm_chart_to_ECR:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: myweb
          repository: helm
          tag: 0.0.5
          path: $GITHUB_WORKSPACE/democharts # Default charts/{name}
          registry: regscalecontainerregistry.azurecr.io
          registry_username: ${{ secrets.ACR_USERNAME }}
          registry_password: ${{ secrets.ACR_PASSWORD }}

# helm pull appany.azurecr.io/helm/my-chart:0.1.0