name: Helm Publish

on:
  push:
    branches: [ echehelm ] 

    # paths-ignore:
    #   - README.md
jobs:
  publish-helmchart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create charts directory
      run: |
        pwd
        mkdir charts
        ls
    - name: copy helm-charts to charts folder
      run: |
        cp -a $GITHUB_WORKSPACE/charts/*.tgz  $GITHUB_WORKSPACE/charts 
        cp -a $GITHUB_WORKSPACE/charts/README.md  $GITHUB_WORKSPACE/charts    

    - name: Create index file
      run: helm repo index $GITHUB_WORKSPACE/charts  

    - name: check content of charts
      run: |
       cd charts
       ls
   #- name: Delete remote branch
    #   run: git push origin --delete gh-pages   
    - name: Create gh-page branch
      run: | 
           git switch --orphan gh-pages
    # - name: Configure git repo 
    #   run: |
    #      git config user.email "${{ secrets.RELEASE_GITHUB_EMAIL }}"
    #      git config user.name "${{ secrets.RELEASE_GITHUB_USER }}"     
    - name: Publish on GitHub Pages
      uses: ftnext/action-push-ghpages@v1.0.0
      with:
       build_dir: charts
       github_token: ${{ secrets.PATOKEN}}       

