name: Helm Publish  To ACR

on:
  push:
    branches: [ echehelm ] 
    

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: latest
  ACR_NAME: regscalecontainerregistry
  ACR_REPO_NAME: helmdemo/vote-app
  ACR_REGISTRY: regscalecontainerregistry
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
  ACR_SERVER: regscalecontainerregistry.azurecr.io
  ACR_HELM_PASSWORD: ${{ secrets.ACR_HELM_PASSWORD }}
jobs:
  push_helm_chart_to_ACR:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - uses: azure/docker-login@v1
        id: login-acr
        with:
          login-server: 'regscalecontainerregistry.azurecr.io' # default: index.docker.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: authenticate helm client
        run: |
            echo ${{ env.ACR_HELM_PASSWORD }}  helm registry login ${{ env.ACR_SERVER }} --username ${{ env.ACR_TOKEN }} --password-stdin    
        
      #    echo ${{ env.ACR_TOKEN }} | helm registry login ${{ env.ACR_SERVER }} --username ${{ env.ACR_USERNAME }} --password-stdin
      #   run : az acr login-password --region us-east-1 | helm registry login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
    
      # - name: helm push  to ECR
      #   run: az acr helm push $GITHUB_WORKSPACE/democharts/*.tgz  -n regscalecontainerregistry #oci://${{ env.ACR_SERVER }}/helm
# - name: login to acr using helm
#   run: |
#     echo $ | helm registry login $.azurecr.io --username $ --password-stdin 