name: Helm Publish  To ACR

on:
  push:
    branches: [ echehelm ] 

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: latest
  ACR_NAME: regscalecontainerregistry
  ACR_REPO_NAME: helmdemo/vote-app

jobs:
  push_helm_chart_to_ECR:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      # - name: install helm
      #   uses: Azure/setup-helm@v1
      #   with:
      #     version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
      - name: login to acr using helm
        run: |
          helm registry login regscalecontainerregistry.azurecr.io --username ${{ secrets.ACR_USERNAME }}$ --password ${{ secrets.ACR_PASSWORD }}

    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: 'regscalecontainerregistry.azurecr.io' # default: index.docker.io
    #     username: ${{ secrets.ACR_USERNAME }}
    #     password: ${{ secrets.ACR_PASSWORD }}
    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1
    # - name: Accessing ECR repo and authenticate helm client
    #   env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #   run : aws ecr get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
    
    # - name: helm push  to ECR
    #   run:  helm push $GITHUB_WORKSPACE/democharts/*.tgz oci://${{ steps.login-ecr.outputs.registry }}/
