name: AWS-Helm Publish  To ECR

on:
  push:
    branches: [ echehelm ] 

jobs:
  push_aws_helm_chart_to_ECR:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Retrieve authentication token
      run : aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 709825985650.dkr.ecr.us-east-1.amazonaws.com    
    - name: Authenticate helm client
      run : |
           export HELM_EXPERIMENTAL_OCI=1
           aws ecr get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin 709825985650.dkr.ecr.us-east-1.amazonaws.com
    - name: helm push  to ECR
      run:  helm push $GITHUB_WORKSPACE/democharts/*.tgz oci://709825985650.dkr.ecr.us-east-1.amazonaws.com/regscale/helm:0.2.0
#      ${{ steps.login-ecr.outputs.registry }}/


