apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWTSecretKey: "{{ .Values.JWTSecretKey }}"
  SQLConn: "{{ .Values.SQLConn }}"
  EncryptionKey: "{{ .Values.EncryptionKey }}"